# Generated by Django 4.1.4 on 2023-01-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecartapp', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
    ]
